#!/usr/bin/env node
// generate-content.mjs
//
// Generates polished promotional copy (LinkedIn + newsletter) for upcoming
// talks and writes them to src/generated/<slug>.md for organizer review.
//
// It always produces deterministic template drafts (the dependable floor from
// src/lib/announcements). If ANTHROPIC_API_KEY is set, it makes an optional
// pass with Claude to tighten the copy — but the script never fails just
// because the key is missing or the API is down; it falls back to templates.
//
// Usage:
//   node scripts/generate-content.mjs            # all upcoming talks
//   node scripts/generate-content.mjs <slug>     # one talk

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DB_PATH = resolve(ROOT, 'data/sessions.json');
const OUT_DIR = resolve(ROOT, 'src/generated');
const MODEL = 'claude-opus-4-8';
const SITE = 'https://cabsweb.net'; // keep in sync with `site` in astro.config.mjs

async function loadSessions() {
  return JSON.parse(await readFile(DB_PATH, 'utf8'));
}

// --- deterministic templates (mirror of src/lib/announcements.ts) ----------

function fmtDate(iso) {
  return new Date(iso).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC',
  });
}
function fmtTime(iso) {
  return new Date(iso).toLocaleTimeString('en-US', {
    hour: 'numeric', minute: '2-digit', timeZone: 'UTC', timeZoneName: 'short',
  });
}
function templateDrafts(s) {
  const tags = ['#CABS', '#AI', '#DigitalProductivity', ...s.tags.map((t) => '#' + t.replace(/[^a-zA-Z0-9]/g, ''))].join(' ');
  const linkedin = [
    `🎙️ Next up in the CABS AI & Digital Productivity Series:`, ``,
    `"${s.title}"`, ``,
    `with ${s.speaker.name}${s.speaker.title ? `, ${s.speaker.title}` : ''}${s.speaker.org ? ` @ ${s.speaker.org}` : ''}`, ``,
    `🗓️ ${fmtDate(s.date)} · ${fmtTime(s.date)}`, `📍 ${s.location}`, ``,
    s.abstract.length > 280 ? s.abstract.slice(0, 277) + '…' : s.abstract, ``,
    `Join us: ${SITE}/events/${s.slug}`, ``, tags,
  ].join('\n');
  const newsletter = [
    `## ${s.title}`, ``,
    `**${s.speaker.name}**, ${s.speaker.title} (${s.speaker.org})`,
    `**When:** ${fmtDate(s.date)}, ${fmtTime(s.date)}  `, `**Where:** ${s.location}`, ``,
    s.abstract, ``,
    `[Details and registration →](${SITE}/events/${s.slug})`,
  ].join('\n');
  return { linkedin, newsletter };
}

// --- optional Claude polish -------------------------------------------------

async function polishWithClaude(session, drafts) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  let Anthropic;
  try {
    ({ default: Anthropic } = await import('@anthropic-ai/sdk'));
  } catch {
    console.warn('  (@anthropic-ai/sdk not installed — skipping AI polish)');
    return null;
  }
  const client = new Anthropic({ apiKey: key });
  const prompt = [
    'You are helping a community AI talk series write promotion copy.',
    'Rewrite the LinkedIn post and newsletter blurb below to be crisp, warm, and engaging.',
    'Keep all facts, links, dates, and hashtags exactly. Do not invent details.',
    'Return JSON: {"linkedin": "...", "newsletter": "..."} and nothing else.',
    '',
    `TALK: ${session.title}`,
    `SPEAKER: ${session.speaker.name}, ${session.speaker.title}, ${session.speaker.org}`,
    '',
    '--- LINKEDIN DRAFT ---', drafts.linkedin,
    '', '--- NEWSLETTER DRAFT ---', drafts.newsletter,
  ].join('\n');

  try {
    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 1500,
      messages: [{ role: 'user', content: prompt }],
    });
    const text = res.content.map((b) => (b.type === 'text' ? b.text : '')).join('');
    const json = text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1);
    return JSON.parse(json);
  } catch (err) {
    console.warn(`  (AI polish failed: ${err.message} — using templates)`);
    return null;
  }
}

function renderMarkdown(session, drafts, aiUsed) {
  return [
    `<!-- generated by scripts/generate-content.mjs — review before posting -->`,
    `# Promotion drafts: ${session.title}`,
    ``,
    `Speaker: ${session.speaker.name} · Date: ${fmtDate(session.date)}`,
    `Copy quality: ${aiUsed ? 'AI-polished (Claude)' : 'template'}`,
    ``,
    `## LinkedIn`, ``, '```', drafts.linkedin, '```', ``,
    `## Newsletter`, ``, '```', drafts.newsletter, '```', ``,
  ].join('\n');
}

async function main() {
  const wantedSlug = process.argv[2];
  const sessions = await loadSessions();
  const targets = sessions.filter(
    (s) => ['scheduled', 'published'].includes(s.status) && (!wantedSlug || s.slug === wantedSlug),
  );

  if (targets.length === 0) {
    console.log('No upcoming talks to generate content for.');
    return;
  }

  await mkdir(OUT_DIR, { recursive: true });
  for (const s of targets) {
    let drafts = templateDrafts(s);
    const polished = await polishWithClaude(s, drafts);
    const aiUsed = Boolean(polished);
    if (polished) drafts = { ...drafts, ...polished };
    const outPath = resolve(OUT_DIR, `${s.slug}.md`);
    await writeFile(outPath, renderMarkdown(s, drafts, aiUsed), 'utf8');
    console.log(`✓ ${s.slug} → src/generated/${s.slug}.md${aiUsed ? ' (AI-polished)' : ''}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
